# Vagrantfile for creating the Jalangi virtualbox. 

Vagrant.configure(2) do |config|
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  #config.vm.box = "ubuntu/trusty64"
  
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update     
#     sudo apt-get install python-software-properties python g++ make
#     sudo apt-get install python-setuptools
#     sudo add-apt-repository -y ppa:chris-lea/node.js
#     sudo apt-get update
#     sudo apt-get install -y nodejs
     sudo add-apt-repository -y ppa:webupd8team/java
     sudo apt-get update
     echo "oracle-java7-installer shared/accepted-oracle-license-v1-1 select true" \
          | sudo debconf-set-selections
     sudo apt-get install -y oracle-java7-installer
     sudo update-java-alternatives -s java-7-oracle
#     sudo apt-get install -y git
#     sudo apt-get install libgmp10
#     sudo apt-get install -y chromium-browser
#     cd Desktop
#     git clone https://github.com/SoftwareEngineeringToolDemos/FSE-2013-Jalangi.git
#     cd FSE-2013-Jalangi
  SHELL
end
